import os

os.chdir("rpi-rgb-led-matrix/bindings/python/samples")
i = 1
while True:
    os.system("python3 uber_fetch.py")   
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 walmart_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 dis_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 amazon_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 spy_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 euro_fetch.py")   
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 exel_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 mro_fetch.py")
    os.system("sudo python ticker_uber.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_walmart.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_dis.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_amazon.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_spy.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_vix.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_euro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_exel.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("sudo python ticker_mro.py -r 16 --led-no-hardware-pulse hi --led-chain=2")
    os.system("python3 vix_fetch.py")
    os.system("sudo python easteregg.py -r 16 --led-no-hardware-pulse hi --led-chain=2")